package uk.gov.justice.laa.crime.microservice.sqstester;

import org.springframework.context.support.DefaultMessageSourceResolvable;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.http.converter.HttpMessageNotReadableException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.context.request.WebRequest;
import org.springframework.web.util.WebUtils;

import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

@ControllerAdvice
public class GlobalExceptionHandler {

    // Handle all exceptions generated by the controller.
    @ExceptionHandler({ MethodArgumentNotValidException.class, HttpMessageNotReadableException.class })
    public final ResponseEntity<ApiError> handleException(Exception ex, WebRequest request) {
        if (ex instanceof MethodArgumentNotValidException) {
            HttpHeaders headers = new HttpHeaders();
            HttpStatus status = HttpStatus.BAD_REQUEST;

            return handleMethodArgumentNotValidException((MethodArgumentNotValidException) ex, headers, status, request);
        } else if (ex instanceof HttpMessageNotReadableException) {
            HttpHeaders headers = new HttpHeaders();
            HttpStatus status = HttpStatus.INTERNAL_SERVER_ERROR;

            return handleHttpMessageNotReadableException((HttpMessageNotReadableException) ex, headers, status, request);
        }

        HttpHeaders headers = new HttpHeaders();
        HttpStatus status = HttpStatus.INTERNAL_SERVER_ERROR;
        return handleExceptionInternal(ex, null, headers, status, request);
    }

    // Customize the response for MethodArgumentNotValidException.
    protected ResponseEntity<ApiError> handleMethodArgumentNotValidException(MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
        List<String> errorMessages = ex.getAllErrors()
                .stream()
                .map(DefaultMessageSourceResolvable::getDefaultMessage)
                .collect(Collectors.toList());

        return handleExceptionInternal(ex, new ApiError(errorMessages), headers, status, request);
    }

    // Customize the response for HttpMessageNotReadableException.
    protected ResponseEntity<ApiError> handleHttpMessageNotReadableException(HttpMessageNotReadableException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
        List<String> errorMessage = Collections.singletonList("Invalid JSON format. Please check you are passing through" +
                " all required values of the correct type.");

        return handleExceptionInternal(ex, new ApiError(errorMessage), headers, status, request);
    }

    // Customize the body of all Exception types.
    protected ResponseEntity<ApiError> handleExceptionInternal(Exception ex, ApiError body, HttpHeaders headers, HttpStatus status, WebRequest request) {
        if (HttpStatus.INTERNAL_SERVER_ERROR.equals(status)) {
            request.setAttribute(WebUtils.ERROR_EXCEPTION_ATTRIBUTE, ex, WebRequest.SCOPE_REQUEST);
        }

        return new ResponseEntity<>(body, headers, status);
    }
}
