package uk.gov.justice.laa.crime.microservice.sqstester;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.http.converter.HttpMessageNotReadableException;
import org.springframework.validation.ObjectError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.context.request.ServletWebRequest;
import org.springframework.web.context.request.WebRequest;
import org.springframework.web.reactive.result.method.annotation.ResponseEntityExceptionHandler;
import org.springframework.web.util.WebUtils;

import java.net.URI;
import java.util.ArrayList;
import java.util.List;

@ControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {

    /**
     * Handle all MethodArgumentNotValidExceptions generated by the controller.
     *
     * @param ex The exception type we are handling
     * @param request The request that has been sent
     * @return A response with a body and status code
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public final ResponseEntity<ApiError> handleException(MethodArgumentNotValidException ex, WebRequest request) {
        HttpHeaders headers = new HttpHeaders();
        HttpStatus status = HttpStatus.BAD_REQUEST;

        List<ProblemDetail> problemList = new ArrayList<ProblemDetail>();

        for (ObjectError error : ex.getAllErrors()) {
            ProblemDetail problemDetail = ProblemDetail.forStatus(status);
            problemDetail.setTitle("Value invalid.");
            problemDetail.setInstance(URI.create(((ServletWebRequest) request).getRequest().getRequestURL().toString()));
            problemDetail.setDetail(error.getDefaultMessage());
            problemList.add(problemDetail);
        }

        return handleExceptionInternal(ex, new ApiError(problemList), headers, status, request);
    }


    /**
     * Handle all HttpMessageNotReadableExceptions generated by the controller.
     *
     * @param ex The exception type we are handling
     * @param request The request that has been sent
     * @return A response with a body and status code
     */
    @ExceptionHandler(HttpMessageNotReadableException.class)
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    public final ResponseEntity<ApiError> handleException(HttpMessageNotReadableException ex, WebRequest request) {
        HttpHeaders headers = new HttpHeaders();
        HttpStatus status = HttpStatus.INTERNAL_SERVER_ERROR;

        ProblemDetail problemDetail = ProblemDetail.forStatus(status);
        problemDetail.setTitle("JSON cannot be parsed.");
        problemDetail.setInstance(URI.create(((ServletWebRequest) request).getRequest().getRequestURL().toString()));
        problemDetail.setDetail("Invalid JSON format. Please check you are passing through all required values of the correct type.");

        return handleExceptionInternal(ex, new ApiError(problemDetail), headers, status, request);
    }

    /**
     * Customize the body of all Exception types.
     *
     * @param ex The exception type we are handling
     * @param body The ApiError with a ProblemDetail or ArrayList of ProblemDetails as the body
     * @param headers The HttpHeaders of the request
     * @param status The status code of the request
     * @param request The request that has been sent
     * @return JSON containing any errors
     */
    protected ResponseEntity<ApiError> handleExceptionInternal(Exception ex, ApiError body, HttpHeaders headers, HttpStatus status, WebRequest request) {
        if (HttpStatus.INTERNAL_SERVER_ERROR.equals(status)) {
            request.setAttribute(WebUtils.ERROR_EXCEPTION_ATTRIBUTE, ex, WebRequest.SCOPE_REQUEST);
        }

        return new ResponseEntity<>(body, headers, status);
    }
}
