app:
  api_username: ${API_USERNAME}
  api_password: ${API_PASSWORD}
springdoc:
  api-docs:
    path: "/api-documentation-raw"
  swagger-ui:
    path: "/api-documentation.html"
cloud:
  aws:
    sqs:
      enabled: ${ENABLE_SPRING_CLOUD_SQS:true}
    stack:
      auto: false
    region:
      static: ${CLOUD_PLATFORM_QUEUE_REGION}
      auto: false
    credentials:
      use-default-aws-credentials-chain: true
cloud-platform:
  aws:
    sqs:
      region: ${CLOUD_PLATFORM_QUEUE_REGION}
      queue:
        link: ${CREATE_LINK_QUEUE}
        unlink: ${UNLINK_QUEUE}
        config:
          messageDelayDuration: 0
sentry:
  dsn: ${SENTRY_DSN}
  environment: ${ENVIRONMENT}
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
